### PR TITLE
2.0.1 Minor env variables addition

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
1. Added `SNP37_VERSION` & `SNP38_VERSION`: add snp database version (e.g. 2.0.1 for our gnomad snps)
2. Added `SNP37_DB` & `SNP38_DB`: add snp database (e.g. gnomad)
3. Aded `PRIMER_VERSION`
4. Changed some wording 'DBSNP' to 'SNP'
5. Removed line 429 - 441 in `primer_designer_region.py` since most gnomad AF>0.01 is considered common

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/3)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @jethror1)

___
*[`README.md` line 25 at r1](https://reviewable.io/reviews/eastgenomics/primer_designer/3#-N6s7WUdEpyDQwq5DFqr:-N6s7WUdEpyDQwq5DFqs:b-jhsc8o) ([raw file](https://github.com/eastgenomics/primer_designer/blob/f367ece35fc2d31901ea0ca00b695db0b4678929/README.md#L25)):*
> ```Markdown
> - [samtools][samtools-url]
> - GRCh37 & GRCh38 human genome reference FASTA files (+ indexes)
> - GRCh37 & GRCh38 common SNPs file (+ indexes)
> ```

VCF file



_Code quote:_
```Markdown
file
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/3)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`output/.keep` line 0 at r1](https://reviewable.io/reviews/eastgenomics/primer_designer/3#-N6xM8jvE5yIJWQJSMnT:-N6xM8jvE5yIJWQJSMnU:bcpagay) ([raw file](https://github.com/eastgenomics/primer_designer/blob/f367ece35fc2d31901ea0ca00b695db0b4678929/output/.keep#L0)):*
do you not need to use the `output` directory? I used the empty `.keep` file to make sure it wasn't deleted for writing output, fine if its not needed now

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/3)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/3)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 25 at r1](https://reviewable.io/reviews/eastgenomics/primer_designer/3#-N6s7WUdEpyDQwq5DFqr:-N70Brgp1cklh9ymB8Ea:b-osacbw) ([raw file](https://github.com/eastgenomics/primer_designer/blob/f367ece35fc2d31901ea0ca00b695db0b4678929/README.md#L25)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

VCF file
</blockquote></details>

changed to vcf / vcf.gz
___
*[`output/.keep` line  at r1](https://reviewable.io/reviews/eastgenomics/primer_designer/3#-N6xM8jvE5yIJWQJSMnT:-N70Bv9ND2CBqlddUW9c:beh4h8z) ([raw file](https://github.com/eastgenomics/primer_designer/blob/f367ece35fc2d31901ea0ca00b695db0b4678929/output/.keep#L)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do you not need to use the `output` directory? I used the empty `.keep` file to make sure it wasn't deleted for writing output, fine if its not needed now
</blockquote></details>

you're right, we still need it. re-added

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/primer_designer/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
